version: "3.8"
services:
  frontend:
    image: femidev/workout-buddy:frontend-v1
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    ports:
      - '3000:3000'
    depends_on:
      - backend
    secrets:
      - react_app_base_url

  backend:
    image: femidev/workout-buddy:backend-v1
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    secrets:
      - port
      - mongodb_uri
      - secret
      - client_url

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

secrets:
  port:
    external: true
  mongodb_uri:
    external: true
  secret:
    external: true
  client_url:
    external: true
  react_app_base_url:
    external: true

volumes:
  mongodb_data:
